import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar/navigation-bar";
import Footer from "@/components/Footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-montserrat w-full flex flex-col justify-center items-center">
        <NavigationBar />
        <main className="max-w-7xl w-full min-h-screen pt-28">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
